### PR TITLE
voting message.en.xlf - fixes some typos and translation

### PR DESCRIPTION
**Pull request by kieranjol**
I just noticed a few typos when you shared that voting link.

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
Much appreciated.
Don't hesitate to review all translations! ;-)

**Comment by kieranjol** [comment]
:)

**Comment by JeromeMartinez** [comment]
@GuillaumeRoques error 500?

**Comment by GuillaumeRoques** [comment]
The error is due to an update of a plugin, I've fixed it in #139 , @kieranjol please rebase your PR to master to fix the tests

**Comment by JeromeMartinez** [comment]
@kieranjol ping?

**Comment by kieranjol** [comment]
I'm hoping that I have rebased correctly. I did it all using the github website and the 'compare' function.

**Comment by JeromeMartinez** [comment]
Thanks!

**Pull request merged**
