### PR TITLE
Add BWF Metaedit announcement post

### PR DESCRIPTION
**Pull request by ablwr**
ATTN @kmurmur

### CODE REVIEW

**Review by JeromeMartinez — APPROVED** [review]

**Comment by kmurmur** [comment]
Sorry for late breaking request but can we change the wording slightly: "Thanks to renewed support from **FADGI and** the Library of Congress"

**Comment by ablwr** [comment]
@kmurmur @JeromeMartinez I will send a patch right now

**Comment by kmurmur** [comment]
Thank you @ablwr!

**Comment by JeromeMartinez** [comment]
@dericed @ablwr @kmurmur it is online (including FADGI related update)
https://mediaarea.net/blog/2020/05/28/announcing-bwf-metaedit-20-05

**Pull request merged**
